// ISO 4217 currencies, with the places that spend them.
//
// The countries are here so the picker can be searched the way people actually
// think: someone quoting a client in Copenhagen types "Denmark", not "DKK".
// Derived from the ISO 4217 register, restricted to codes our rate feed
// actually quotes — offering a currency we cannot convert would put a deal in
// the pipeline that no total could count.
//
// 166 currencies covering 248 countries and territories.
// The one inhabited place with no quotable currency is North Korea (KPW); no FX
// feed prices it. Metals (XAU, XAG), fund units (BOV, CHE, USN…) and the
// testing codes (XTS, XXX) are ISO currencies but not money you quote work in,
// so they are deliberately absent.

export interface CurrencyMeta {
  name: string
  countries: string[]
}

export const CURRENCY_META: Record<string, CurrencyMeta> = {
  AED: { name: "UAE Dirham", countries: ["United Arab Emirates"] },
  AFN: { name: "Afghani", countries: ["Afghanistan"] },
  ALL: { name: "Lek", countries: ["Albania"] },
  AMD: { name: "Armenian Dram", countries: ["Armenia"] },
  ANG: { name: "Netherlands Antillean Guilder", countries: ["Curaçao", "Sint Maarten"] },
  AOA: { name: "Kwanza", countries: ["Angola"] },
  ARS: { name: "Argentine Peso", countries: ["Argentina"] },
  AUD: { name: "Australian Dollar", countries: ["Australia", "Christmas Island", "Cocos (Keeling) Islands", "Heard Island and Mcdonald Islands", "Kiribati", "Nauru", "Norfolk Island", "Tuvalu"] },
  AWG: { name: "Aruban Florin", countries: ["Aruba"] },
  AZN: { name: "Azerbaijan Manat", countries: ["Azerbaijan"] },
  BAM: { name: "Convertible Mark", countries: ["Bosnia and Herzegovina"] },
  BBD: { name: "Barbados Dollar", countries: ["Barbados"] },
  BDT: { name: "Taka", countries: ["Bangladesh"] },
  BGN: { name: "Bulgarian Lev", countries: ["Bulgaria"] },
  BHD: { name: "Bahraini Dinar", countries: ["Bahrain"] },
  BIF: { name: "Burundi Franc", countries: ["Burundi"] },
  BMD: { name: "Bermudian Dollar", countries: ["Bermuda"] },
  BND: { name: "Brunei Dollar", countries: ["Brunei Darussalam"] },
  BOB: { name: "Boliviano", countries: ["Bolivia (Plurinational State of)"] },
  BRL: { name: "Brazilian Real", countries: ["Brazil"] },
  BSD: { name: "Bahamian Dollar", countries: ["Bahamas"] },
  BTN: { name: "Ngultrum", countries: ["Bhutan"] },
  BWP: { name: "Pula", countries: ["Botswana"] },
  BYN: { name: "Belarusian Ruble", countries: ["Belarus"] },
  BZD: { name: "Belize Dollar", countries: ["Belize"] },
  CAD: { name: "Canadian Dollar", countries: ["Canada"] },
  CDF: { name: "Congolese Franc", countries: ["Congo (Democratic Republic of the)"] },
  CHF: { name: "Swiss Franc", countries: ["Liechtenstein", "Switzerland"] },
  CLF: { name: "Unidad de Fomento", countries: ["Chile"] },
  CLP: { name: "Chilean Peso", countries: ["Chile"] },
  CNH: { name: "Chinese Yuan (offshore)", countries: ["China (offshore)", "Hong Kong"] },
  CNY: { name: "Yuan Renminbi", countries: ["China"] },
  COP: { name: "Colombian Peso", countries: ["Colombia"] },
  CRC: { name: "Costa Rican Colon", countries: ["Costa Rica"] },
  CUP: { name: "Cuban Peso", countries: ["Cuba"] },
  CVE: { name: "Cabo Verde Escudo", countries: ["Cabo Verde"] },
  CZK: { name: "Czech Koruna", countries: ["Czechia"] },
  DJF: { name: "Djibouti Franc", countries: ["Djibouti"] },
  DKK: { name: "Danish Krone", countries: ["Denmark", "Faroe Islands", "Greenland"] },
  DOP: { name: "Dominican Peso", countries: ["Dominican Republic"] },
  DZD: { name: "Algerian Dinar", countries: ["Algeria"] },
  EGP: { name: "Egyptian Pound", countries: ["Egypt"] },
  ERN: { name: "Nakfa", countries: ["Eritrea"] },
  ETB: { name: "Ethiopian Birr", countries: ["Ethiopia"] },
  EUR: { name: "Euro", countries: ["Åland Islands", "Andorra", "Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus", "Estonia", "European Union", "Finland", "France", "French Guiana", "French Southern Territories", "Germany", "Greece", "Guadeloupe", "Holy See", "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Malta", "Martinique", "Mayotte", "Monaco", "Montenegro", "Netherlands", "Portugal", "Réunion", "Saint Barthélemy", "Saint Martin (French Part)", "Saint Pierre and Miquelon", "San Marino", "Slovakia", "Slovenia", "Spain"] },
  FJD: { name: "Fiji Dollar", countries: ["Fiji"] },
  FKP: { name: "Falkland Islands Pound", countries: ["Falkland Islands (the) [Malvinas]"] },
  FOK: { name: "Faroese Króna", countries: ["Faroe Islands"] },
  GBP: { name: "Pound Sterling", countries: ["Guernsey", "Isle of Man", "Jersey", "United Kingdom of Great Britain and Northern Ireland"] },
  GEL: { name: "Lari", countries: ["Georgia"] },
  GGP: { name: "Guernsey Pound", countries: ["Guernsey"] },
  GHS: { name: "Ghana Cedi", countries: ["Ghana"] },
  GIP: { name: "Gibraltar Pound", countries: ["Gibraltar"] },
  GMD: { name: "Dalasi", countries: ["Gambia"] },
  GNF: { name: "Guinean Franc", countries: ["Guinea"] },
  GTQ: { name: "Quetzal", countries: ["Guatemala"] },
  GYD: { name: "Guyana Dollar", countries: ["Guyana"] },
  HKD: { name: "Hong Kong Dollar", countries: ["Hong Kong"] },
  HNL: { name: "Lempira", countries: ["Honduras"] },
  HRK: { name: "Croatian Kuna", countries: ["Croatia"] },
  HTG: { name: "Gourde", countries: ["Haiti"] },
  HUF: { name: "Forint", countries: ["Hungary"] },
  IDR: { name: "Rupiah", countries: ["Indonesia"] },
  ILS: { name: "New Israeli Sheqel", countries: ["Israel"] },
  IMP: { name: "Isle of Man Pound", countries: ["Isle of Man"] },
  INR: { name: "Indian Rupee", countries: ["Bhutan", "India"] },
  IQD: { name: "Iraqi Dinar", countries: ["Iraq"] },
  IRR: { name: "Iranian Rial", countries: ["Iran (Islamic Republic of)"] },
  ISK: { name: "Iceland Krona", countries: ["Iceland"] },
  JEP: { name: "Jersey Pound", countries: ["Jersey"] },
  JMD: { name: "Jamaican Dollar", countries: ["Jamaica"] },
  JOD: { name: "Jordanian Dinar", countries: ["Jordan"] },
  JPY: { name: "Yen", countries: ["Japan"] },
  KES: { name: "Kenyan Shilling", countries: ["Kenya"] },
  KGS: { name: "Som", countries: ["Kyrgyzstan"] },
  KHR: { name: "Riel", countries: ["Cambodia"] },
  KID: { name: "Kiribati Dollar", countries: ["Kiribati"] },
  KMF: { name: "Comorian Franc ", countries: ["Comoros"] },
  KRW: { name: "Won", countries: ["Korea (Republic of)"] },
  KWD: { name: "Kuwaiti Dinar", countries: ["Kuwait"] },
  KYD: { name: "Cayman Islands Dollar", countries: ["Cayman Islands"] },
  KZT: { name: "Tenge", countries: ["Kazakhstan"] },
  LAK: { name: "Lao Kip", countries: ["Lao People'S Democratic Republic"] },
  LBP: { name: "Lebanese Pound", countries: ["Lebanon"] },
  LKR: { name: "Sri Lanka Rupee", countries: ["Sri Lanka"] },
  LRD: { name: "Liberian Dollar", countries: ["Liberia"] },
  LSL: { name: "Loti", countries: ["Lesotho"] },
  LYD: { name: "Libyan Dinar", countries: ["Libya"] },
  MAD: { name: "Moroccan Dirham", countries: ["Morocco", "Western Sahara"] },
  MDL: { name: "Moldovan Leu", countries: ["Moldova (Republic of)"] },
  MGA: { name: "Malagasy Ariary", countries: ["Madagascar"] },
  MKD: { name: "Denar", countries: ["North Macedonia"] },
  MMK: { name: "Kyat", countries: ["Myanmar"] },
  MNT: { name: "Tugrik", countries: ["Mongolia"] },
  MOP: { name: "Pataca", countries: ["Macao"] },
  MRU: { name: "Ouguiya", countries: ["Mauritania"] },
  MUR: { name: "Mauritius Rupee", countries: ["Mauritius"] },
  MVR: { name: "Rufiyaa", countries: ["Maldives"] },
  MWK: { name: "Malawi Kwacha", countries: ["Malawi"] },
  MXN: { name: "Mexican Peso", countries: ["Mexico"] },
  MYR: { name: "Malaysian Ringgit", countries: ["Malaysia"] },
  MZN: { name: "Mozambique Metical", countries: ["Mozambique"] },
  NAD: { name: "Namibia Dollar", countries: ["Namibia"] },
  NGN: { name: "Naira", countries: ["Nigeria"] },
  NIO: { name: "Cordoba Oro", countries: ["Nicaragua"] },
  NOK: { name: "Norwegian Krone", countries: ["Bouvet Island", "Norway", "Svalbard and Jan Mayen"] },
  NPR: { name: "Nepalese Rupee", countries: ["Nepal"] },
  NZD: { name: "New Zealand Dollar", countries: ["Cook Islands", "New Zealand", "Niue", "Pitcairn", "Tokelau"] },
  OMR: { name: "Rial Omani", countries: ["Oman"] },
  PAB: { name: "Balboa", countries: ["Panama"] },
  PEN: { name: "Sol", countries: ["Peru"] },
  PGK: { name: "Kina", countries: ["Papua New Guinea"] },
  PHP: { name: "Philippine Peso", countries: ["Philippines"] },
  PKR: { name: "Pakistan Rupee", countries: ["Pakistan"] },
  PLN: { name: "Zloty", countries: ["Poland"] },
  PYG: { name: "Guarani", countries: ["Paraguay"] },
  QAR: { name: "Qatari Rial", countries: ["Qatar"] },
  RON: { name: "Romanian Leu", countries: ["Romania"] },
  RSD: { name: "Serbian Dinar", countries: ["Serbia"] },
  RUB: { name: "Russian Ruble", countries: ["Russian Federation"] },
  RWF: { name: "Rwanda Franc", countries: ["Rwanda"] },
  SAR: { name: "Saudi Riyal", countries: ["Saudi Arabia"] },
  SBD: { name: "Solomon Islands Dollar", countries: ["Solomon Islands"] },
  SCR: { name: "Seychelles Rupee", countries: ["Seychelles"] },
  SDG: { name: "Sudanese Pound", countries: ["Sudan"] },
  SEK: { name: "Swedish Krona", countries: ["Sweden"] },
  SGD: { name: "Singapore Dollar", countries: ["Singapore"] },
  SHP: { name: "Saint Helena Pound", countries: ["Saint Helena, Ascension and Tristan da Cunha"] },
  SLE: { name: "Leone", countries: ["Sierra Leone"] },
  SLL: { name: "Sierra Leonean Leone (old)", countries: ["Sierra Leone"] },
  SOS: { name: "Somali Shilling", countries: ["Somalia"] },
  SRD: { name: "Surinam Dollar", countries: ["Suriname"] },
  SSP: { name: "South Sudanese Pound", countries: ["South Sudan"] },
  STN: { name: "Dobra", countries: ["Sao Tome and Principe"] },
  SYP: { name: "Syrian Pound", countries: ["Syrian Arab Republic"] },
  SZL: { name: "Lilangeni", countries: ["Eswatini"] },
  THB: { name: "Baht", countries: ["Thailand"] },
  TJS: { name: "Somoni", countries: ["Tajikistan"] },
  TMT: { name: "Turkmenistan New Manat", countries: ["Turkmenistan"] },
  TND: { name: "Tunisian Dinar", countries: ["Tunisia"] },
  TOP: { name: "Pa’anga", countries: ["Tonga"] },
  TRY: { name: "Turkish Lira", countries: ["Türki̇ye"] },
  TTD: { name: "Trinidad and Tobago Dollar", countries: ["Trinidad and Tobago"] },
  TVD: { name: "Tuvaluan Dollar", countries: ["Tuvalu"] },
  TWD: { name: "New Taiwan Dollar", countries: ["Taiwan (Province of China)"] },
  TZS: { name: "Tanzanian Shilling", countries: ["Tanzania, United Republic of"] },
  UAH: { name: "Hryvnia", countries: ["Ukraine"] },
  UGX: { name: "Uganda Shilling", countries: ["Uganda"] },
  USD: { name: "US Dollar", countries: ["American Samoa", "Bonaire, Sint Eustatius and Saba", "British Indian Ocean Territory", "Ecuador", "El Salvador", "Guam", "Haiti", "Marshall Islands", "Micronesia (Federated States of)", "Northern Mariana Islands", "Palau", "Panama", "Puerto Rico", "Timor-Leste", "Turks and Caicos Islands", "United States Minor Outlying Islands", "United States of America", "Virgin Islands (British)", "Virgin Islands (U.S.)"] },
  UYU: { name: "Peso Uruguayo", countries: ["Uruguay"] },
  UZS: { name: "Uzbekistan Sum", countries: ["Uzbekistan"] },
  VES: { name: "Bolívar Soberano", countries: ["Venezuela (Bolivarian Republic of)"] },
  VND: { name: "Dong", countries: ["Viet Nam"] },
  VUV: { name: "Vatu", countries: ["Vanuatu"] },
  WST: { name: "Tala", countries: ["Samoa"] },
  XAF: { name: "CFA Franc BEAC", countries: ["Cameroon", "Central African Republic", "Chad", "Congo", "Equatorial Guinea", "Gabon"] },
  XCD: { name: "East Caribbean Dollar", countries: ["Anguilla", "Antigua and Barbuda", "Dominica", "Grenada", "Montserrat", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines"] },
  XCG: { name: "Caribbean Guilder", countries: ["Curaçao", "Sint Maarten (Dutch Part)"] },
  XDR: { name: "SDR (Special Drawing Right)", countries: [] },
  XOF: { name: "CFA Franc BCEAO", countries: ["Benin", "Burkina Faso", "Côte D'Ivoire", "Guinea-Bissau", "Mali", "Niger", "Senegal", "Togo"] },
  XPF: { name: "CFP Franc", countries: ["French Polynesia", "New Caledonia", "Wallis and Futuna"] },
  YER: { name: "Yemeni Rial", countries: ["Yemen"] },
  ZAR: { name: "Rand", countries: ["Lesotho", "Namibia", "South Africa"] },
  ZMW: { name: "Zambian Kwacha", countries: ["Zambia"] },
  ZWG: { name: "Zimbabwe Gold", countries: ["Zimbabwe"] },
  ZWL: { name: "Zimbabwean Dollar", countries: ["Zimbabwe"] },
}
